'use strict';
const assert = require('node:assert/strict');
const { project } = require('../frontend/app/overseer.js');
const threads = { home: { id: 'home' }, research: { id: 'research', title: 'Research' }, other: { id: 'other', title: 'Other' } };
const get = id => threads[id];
const worker = (runId, status, startedAt, extra = {}) => ({ id: runId, runId, status, startedAt, parentStreamId: 'home', streamId: 'research', ...extra });
let rows = project({ workers: [worker('old', 'error', 1), worker('new', 'done', 2)], reviews: [{ workerRunId: 'new', status: 'done' }] }, get);
assert.equal(rows.length, 1);
assert.equal(rows[0].status, 'Reviewed', 'latest result wins regardless of persisted record order');
rows = project({ workers: [worker('active', 'running', 1), worker('done', 'done', 2)] }, get);
assert.equal(rows[0].status, 'Starting', 'an unconfirmed active run stays visible without claiming work started');
rows = project({ workers: [worker('active', 'running', 1, { working: true }), worker('bad', 'error', 2, { streamId: 'other' })] }, get);
assert.equal(rows[0].title, 'Other', 'unresolved issues precede active work');
assert.equal(rows[1].status, 'Working');
rows = project({ workers: [worker('bad', 'error', 2)], reviews: [{ workerRunId: 'bad', status: 'done' }] }, get);
assert.equal(rows[0].status, 'Issue reported', 'a reviewed failure is not an unresolved review or a successful worker');
assert.equal(rows[0].parentId, 'home', 'review opens the originating conversation');
rows = project({ paused: true, workers: [worker('done', 'done', 2)] }, get);
assert.equal(rows[0].status, 'Review paused');
rows = project({ workers: [worker('done', 'done', 2)], reviews: [{ workerRunId: 'done', status: 'pending', error: 'Connect the overseer provider.' }] }, get);
assert.equal(rows[0].group, 0);
assert.equal(rows[0].detail, 'Connect the overseer provider.', 'recovery reason is visible text');
assert.deepEqual(project({ workers: [worker('gone', 'done', 1, { parentStreamId: 'deleted' })] }, get), []);
console.log('overseer UI: truthful status, chronology, failure review and recovery routing PASS');
