/* New Horizon: a separate world client. Imports mechanics and backend contracts, never the former visual client. */
'use strict';
(async()=>{
 const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const canvas=$('world'),scene=NextScene.create(canvas),sim=NextSimulation.create(),bridge=NextBridge.create({WorldModel,Pipeline});
 const catalog=(await fetch('catalog.json').then(r=>{if(!r.ok)throw Error('Catalog could not load');return r.json();})).items;
 const specs=new Map(catalog.map(x=>[x.id,x]));WorldModel.setPropRules(id=>specs.get(id)||null);
 let art,characters,model,station,state={},stationKey='',rosterKey='',selectedAgent=null,selectedProp=null,panel=null,tool='select',armedType='plant',rotation=0,roomKind='hab',finish='bone',material='ceramic',quality='high',follow=false;
 let drag=null,preview=null,beltFrom=null,saveTimer=null,last=performance.now(),lastDom=0,toastTimer=null,lastConversation='';
 let localRevision=0,savedRevision=0,renderedProps=[];
 const camera={x:320,y:180,zoom:.9};
 const rect=(a,b)=>({x1:Math.min(a.x,b.x),y1:Math.min(a.y,b.y),x2:Math.max(a.x,b.x),y2:Math.max(a.y,b.y)});
 const point=e=>{const r=canvas.getBoundingClientRect();return{x:camera.x+(e.clientX-r.left-r.width/2)/camera.zoom,y:camera.y+(e.clientY-r.top-r.height/2)/camera.zoom};};
 const tile=e=>{const p=point(e);return{x:Math.floor(p.x/32),y:Math.floor(p.y/32)};};
 const online=()=>state.connection&&['connected','online'].includes(state.connection.status);
 const roster=()=>Array.isArray(state.roster)?state.roster:state.roster&&state.roster.agents||[];
 const aid=a=>a.id||a.agentId;
 const agent=()=>roster().find(a=>aid(a)===selectedAgent)||roster()[0];
 function toast(text){$('toast').textContent=String(text);$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4200);}
 function fit(){if(!station)return;const b=NextScene.bounds(station);camera.x=b.cx;camera.y=b.cy;camera.zoom=Math.min(1.05,(innerWidth-180)/b.width,(innerHeight-200)/b.height);follow=false;}
 function focusRoom(id){const r=station&&station.rooms[id];if(!r)return;const rs=r.rects;const x1=Math.min(...rs.map(x=>x.x1)),x2=Math.max(...rs.map(x=>x.x2)),y1=Math.min(...rs.map(x=>x.y1)),y2=Math.max(...rs.map(x=>x.y2));camera.x=(x1+x2+1)*16;camera.y=(y1+y2+1)*16-22;camera.zoom=Math.min(1.2,(innerWidth-280)/((x2-x1+5)*32),(innerHeight-180)/((y2-y1+5)*32));follow=false;}
 function updateStation(doc){station=doc;stationKey=JSON.stringify(doc);renderedProps=doc.props.map(p=>{const host=model.mountOf(p)==="surface"?model.surfaceHostOf(p):null;return host?{...p,host,mountRise:20}:p;});sim.setStation(model);sim.setRoster(roster());$('station-name').textContent=doc.meta&&doc.meta.name||'YOUR STATION';$('room-nav').replaceChildren();for(const r of Object.values(doc.rooms||{})){if(r.kind==='corridor')continue;const b=document.createElement('button');b.textContent=r.name;b.onclick=()=>focusRoom(r.id);$('room-nav').append(b);}historyState();}
 function historyState(){$('undo').disabled=!model||!model.canUndo();$('redo').disabled=!model||!model.canRedo();}
 async function save(){if(!model)return;clearTimeout(saveTimer);$('save-state').textContent='Saving…';try{const revision=localRevision,receipt=await bridge.saveStation(model.serialize());savedRevision=Math.max(savedRevision,revision);$('save-state').textContent=receipt.routingError?'Saved · routing needs attention':localRevision===savedRevision?'Station saved':'Unsaved edits';if(receipt.routingError)toast(receipt.routingError);}catch(e){$('save-state').textContent='Save needs attention';toast(e.message);}}
 function changed(result){if(!result||!result.ok){toast(result&&result.msg||result&&result.error||'That placement is not valid');return false;}localRevision++;updateStation(model.serialize());$('save-state').textContent='Unsaved edits';clearTimeout(saveTimer);saveTimer=setTimeout(save,300);if(selectedProp)inspectProp(selectedProp);return true;}
 function crewState(){const a=sim.actors();$('crew-count').textContent=String(a.length);const current=$('crew-list');const signature=a.map(x=>x.id+':'+x.name+':'+x.working+':'+x.waiting+':'+x.workUnknown+':'+(x.id===selectedAgent)).join('|');if(current.dataset.signature===signature)return;current.dataset.signature=signature;current.replaceChildren();a.forEach((a,i)=>{const b=document.createElement('button');b.className='crew-card'+(a.id===selectedAgent?' selected':'');b.dataset.working=String(a.working);b.setAttribute('aria-label','Select '+a.name);const img=document.createElement('img');img.className='crew-portrait';img.src=characters?characters.portrait(a.appearance):'';img.alt='';const text=document.createElement('span'),name=document.createElement('strong'),small=document.createElement('small');name.textContent=a.name;small.textContent=a.workUnknown?'Activity unconfirmed':a.waiting?'Waiting for your input':a.working?'Working on a task':'At ease';text.append(name,small);const dot=document.createElement('span');dot.className='status-light';b.append(img,text,dot);b.onclick=()=>{selectedAgent=a.id;crewState();openPanel('comms');};current.append(b);});}
 function closePanel(){panel=null;$('panel').hidden=true;tool='select';preview=null;document.querySelectorAll('[data-panel]').forEach(b=>b.classList.remove('active'));$('world-hint').textContent='Drag to look around · Scroll to zoom · Shift-click to walk';}
 function openPanel(name){panel=name;selectedProp=null;$('inspector').hidden=true;$('panel').hidden=false;$('panel').className='panel'+(name==='comms'?' comms':'');$('panel-kicker').textContent=name==='build'?'SHAPE YOUR STATION':name==='comms'?'DIRECT LINK':name==='work'?'REAL HARNESS ACTIVITY':'STATION CREW';$('panel-title').textContent={build:'Make it your world',comms:agent()?.name||'Comms',work:'Work in motion',crew:'People & capabilities',settings:'World settings',records:'Recorded work'}[name]||'Station';document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));({build:buildPanel,comms:commsPanel,work:workPanel,crew:capabilityPanel,settings:settingsPanel,records:recordsPanel}[name]||workPanel)();}
 function buildPanel(){
  $('panel-body').innerHTML='<div class="tool-grid">'+[['select','Inspect'],['room','Room'],['hall','Corridor'],['prop','Objects'],['paint','Surfaces'],['belt','Conveyor'],['move','Move'],['erase','Remove']].map(([id,n])=>'<button data-tool="'+id+'" class="'+(tool===id?'active':'')+'">'+n+'</button>').join('')+'</div><div id="build-options"></div>';
  $('panel-body').querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;beltFrom=null;buildPanel();});const box=$('build-options');
  const hints={select:'Click an object to inspect its real function.',room:'Drag a room footprint. It must not overlap another room.',hall:'Drag a two-tile corridor between room edges.',prop:'Pick an object, then click to place. R turns its facing.',paint:'Choose a finish, then click a room to repaint it.',belt:'Click a source machine, then a destination. The routing compiler validates the line.',move:'Drag a room or object to relocate it.',erase:'Click a prop or room to remove it. Undo restores the edit.'};$('world-hint').textContent=hints[tool];
  if(tool==='room'){box.innerHTML='<p class="muted">Every room is editable space. Its equipment supplies the real capabilities.</p><div class="section-title">Room character</div><div class="chip-row">'+WorldModel.KIND_ORDER.filter(k=>k!=='corridor').map(k=>'<button class="chip '+(roomKind===k?'active':'')+'" data-kind="'+k+'">'+esc(WorldModel.ROOM_KINDS[k].label)+'</button>').join('')+'</div>';box.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{roomKind=b.dataset.kind;buildPanel();});}
  else if(tool==='paint'){box.innerHTML='<span class="field-label">Finish</span><select id="finish">'+Object.entries(WorldModel.FLOOR_STYLES).map(([id,v])=>'<option value="'+id+'" '+(id===finish?'selected':'')+'>'+esc(v.label||id)+'</option>').join('')+'</select><span class="field-label">Material</span><select id="material">'+WorldModel.MAT_ORDER.map(id=>'<option value="'+id+'" '+(id===material?'selected':'')+'>'+esc(WorldModel.FLOOR_MATERIALS[id].label||id)+'</option>').join('')+'</select><p class="muted">The fresh environment renderer interprets the same saved material choices.</p>';$('finish').onchange=e=>finish=e.target.value;$('material').onchange=e=>material=e.target.value;}
  else if(tool==='prop'){
   box.innerHTML='<input id="catalog-search" aria-label="Search objects" placeholder="Find equipment, furniture, plants…"><div class="action-row"><button class="action" id="turn-armed">Turn · '+['S','W','N','E'][rotation]+'</button><select id="catalog-category" aria-label="Object category"><option value="">All objects</option>'+[...new Set(catalog.map(p=>p.cat))].map(c=>'<option>'+esc(c)+'</option>').join('')+'</select></div><div id="catalog-grid" class="catalog-grid"></div><p class="muted">'+catalog.length+' existing object identities; every displayed object uses the new art system.</p>';
   const filter=()=>{const q=$('catalog-search').value.toLowerCase(),cat=$('catalog-category').value;const rows=catalog.filter(p=>(!cat||p.cat===cat)&&[p.id,p.label,p.desc].join(' ').toLowerCase().includes(q)).slice(0,60);$('catalog-grid').replaceChildren();for(const s of rows){const b=document.createElement('button');b.className='catalog-item'+(s.id===armedType?' active':'');b.setAttribute('aria-label','Place '+s.label);const cv=document.createElement('canvas');cv.width=96;cv.height=80;const g=cv.getContext('2d');g.imageSmoothingEnabled=false;g.save();const scale=Math.min(80/(s.w*32+20),60/(s.h*32+44),.95);g.translate(48,68);g.scale(scale,scale);g.translate(-s.w*16,-s.h*32);art.drawProp(g,{t:s.id,x:0,y:0,w:s.w,h:s.h},0,{working:false});g.restore();const label=document.createElement('span');label.textContent=s.label;b.append(cv,label);b.onclick=()=>{armedType=s.id;rotation=NextOrientation.facings(s)[0];$('turn-armed').disabled=!s.canRotate;$('turn-armed').textContent='Turn · '+['S','W','N','E'][rotation];filter();};$('catalog-grid').append(b);}};
   $('catalog-search').oninput=filter;$('catalog-category').onchange=filter;$('turn-armed').onclick=()=>{rotation=NextOrientation.nextFacing(specs.get(armedType),rotation);$('turn-armed').textContent='Turn · '+['S','W','N','E'][rotation];};$('turn-armed').disabled=!specs.get(armedType)?.canRotate;filter();
  }else box.innerHTML='<p class="muted">'+hints[tool]+'</p>';
 }
 function recordsPanel(){NextRecords.mount({host:$('panel-body'),bridge,agentId:selectedAgent,onError:toast});}
 function conversation(){return(state.conversations||{})[selectedAgent]||{messages:[],status:'idle'};}
 function renderMessages(){if(panel!=='comms'||!$('transcript'))return;const c=conversation(),signature=JSON.stringify(c);if(signature===lastConversation)return;lastConversation=signature;const holder=$('transcript');holder.replaceChildren();for(const msg of c.messages||[]){const d=document.createElement('div');d.className='message '+(msg.role==='user'?'user':'');const who=document.createElement('span');who.className='speaker';who.textContent=msg.role==='user'?'YOU':agent()?.name||'CREW';const text=document.createElement('span');text.textContent=typeof msg.content==='string'?msg.content:msg.text||'';d.append(who,text);holder.append(d);}if(c.text&&!(c.messages||[]).some(m=>m.content===c.text)){const d=document.createElement('div');d.className='message';d.textContent=c.text;holder.append(d);}if(!holder.childNodes.length){const p=document.createElement('p');p.className='muted';p.textContent='Talk to '+(agent()?.name||'your crew')+'. Messages run through the real StarNet harness.';holder.append(p);}$('run-state').textContent=c.error||({connecting:'Connecting to the harness…',running:'Working on your request',working:'Working on your request',streaming:'Receiving response',done:'Task completed',complete:'Task completed',ended:'Run ended',waiting:'Waiting for your input',error:'Run needs attention',failed:'Task failed',idle:''}[c.status]||c.status||'');$('send-message').disabled=['connecting','running','working','streaming','waiting'].includes(c.status);holder.scrollTop=holder.scrollHeight;}
 function commsPanel(){const a=agent();if(a)selectedAgent=aid(a);$('panel-body').innerHTML='<div id="transcript" class="transcript" aria-live="polite"></div><div id="run-state" class="run-state"></div><textarea id="message-input" aria-label="Message crew member" placeholder="What shall we work on?"></textarea><div class="action-row"><button id="send-message" class="action primary">Send message ↗</button><button id="stop-message" class="action">Stop</button></div><div id="permission-prompts"></div><button id="view-records" class="text-button">Read saved conversations & deliverables ↗</button>';$('view-records').onclick=()=>openPanel('records');lastConversation='';renderMessages();const send=async()=>{const text=$('message-input').value.trim();if(!text||!selectedAgent)return;$('message-input').value='';try{await bridge.send(selectedAgent,text);}catch(e){toast(e.message);}renderMessages();};$('send-message').onclick=send;$('message-input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}};$('stop-message').onclick=()=>{const c=conversation();if(c.runId)bridge.stopRun(c.runId).catch(e=>toast(e.message));};renderPrompts();}
 function renderPrompts(){
  const host=$('permission-prompts');if(!host)return;
  const prompts=(state.prompts||[]).filter(p=>!p.agentId||p.agentId===selectedAgent),signature=JSON.stringify(prompts);if(host.dataset.signature===signature)return;host.dataset.signature=signature;host.replaceChildren();
  for(const p of prompts){let args={};try{args=typeof p.argsSummary==='string'?JSON.parse(p.argsSummary):p.argsSummary||{};}catch(_){}
   const question=p.tool==='brief.ask',row=document.createElement('div');row.className='run-card';const title=document.createElement('b');title.textContent=question?(args.question||'The crew needs your input'):'Permission requested: '+(p.tool||p.scope||'Action');row.append(title);
   const detail=document.createElement('p');detail.className='muted';detail.textContent=question?(args.context||args.reason||''):(typeof p.argsSummary==='string'?p.argsSummary:JSON.stringify(p.argsSummary||{}));row.append(detail);
   const respond=async fn=>{row.querySelectorAll('button').forEach(b=>b.disabled=true);try{const receipt=await fn();if(!receipt||receipt.ok!==true)throw Error(receipt?.error||'The harness did not accept the response.');row.remove();}catch(e){row.querySelectorAll('button').forEach(b=>b.disabled=false);toast(e.message);}};
   if(!question){for(const [value,label]of [['once','Allow once'],['deny','Deny']]){const b=document.createElement('button');b.className='action';b.textContent=label;b.onclick=()=>respond(()=>bridge.respondPermission(p.runId,p.promptId,value));row.append(b);}}
   else{const input=document.createElement('textarea');input.setAttribute('aria-label','Answer harness question');for(const option of args.options||[]){const b=document.createElement('button');b.className='action';const text=typeof option==='string'?option:option.label||option.value;b.textContent=text;b.onclick=()=>{input.value=text;};row.append(b);}const b=document.createElement('button');b.className='action';b.textContent='Reply';b.onclick=()=>respond(()=>bridge.answerPrompt(p.runId,p.promptId,input.value));row.append(input,b);}
   host.append(row);if(p.runId&&p.promptId)bridge.acknowledgePrompt(p.runId,p.promptId).catch(e=>toast(e.message));
  }
 }
 function workPanel(){const runs=state.runs||[];$('panel-body').innerHTML='<p class="muted">These records come from the harness. World animation never creates a task or a completion.</p><div id="run-list"></div><div class="section-title">Conveyor routing</div><div id="routing-result"></div>';const list=$('run-list');if(!runs.length)list.innerHTML='<p class="muted">No run records have been received.</p>';for(const r of runs.slice(-20).reverse()){const d=document.createElement('div');d.className='run-card';const title=document.createElement('b');title.textContent=r.title||r.prompt||r.agentId||r.id||r.runId;const sub=document.createElement('small');sub.textContent=[r.status||r.state||'Unknown state',r.runId||r.id].filter(Boolean).join(' · ');d.append(title,sub);list.append(d);}try{const p=Pipeline.compileRoutingPlan(model.projectGeometry());$('routing-result').textContent=(p.errors||[]).length?(p.errors||[]).map(e=>e.msg||e.message||e.code||JSON.stringify(e)).join('\n'):'The current layout compiles without routing warnings.';}catch(e){$('routing-result').textContent=e.message;}}
 function capabilityPanel(){const a=agent();$('panel-body').innerHTML='<span class="field-label">Crew member</span><select id="crew-picker" aria-label="Inspect crew">'+roster().map(r=>'<option value="'+esc(aid(r))+'" '+(aid(r)===selectedAgent?'selected':'')+'>'+esc(r.name||aid(r))+'</option>').join('')+'</select><p class="muted">'+esc(a?.purpose||a?.role||'Station crew')+'</p><div class="section-title">Capability projection</div><div id="capabilities"></div><div class="action-row"><button class="action" id="crew-focus">Find in world</button><button class="action primary" id="crew-talk">Talk</button></div>';$('crew-picker').onchange=e=>{selectedAgent=e.target.value;capabilityPanel();crewState();};const caps=(state.capabilities||{})[selectedAgent];const items=Array.isArray(caps)?caps:caps&&Array.isArray(caps.toolsets)?caps.toolsets:caps&&Array.isArray(caps.capabilities)?caps.capabilities:[];if(!items.length)$('capabilities').innerHTML='<p class="muted">'+(caps?.error|| (caps?'No capabilities in this projection.':'Capability details have not been received.'))+'</p>';for(const c of items){const row=document.createElement('div');row.className='capability';const name=document.createElement('b'),detail=document.createElement('small');name.textContent=typeof c==='string'?c:c.label||c.objectType||c.type;detail.textContent=typeof c==='string'?'':(c.available?'Available':'Unavailable')+' · '+(c.toolCount||0)+' tools'+(c.grantSource?' · '+c.grantSource:'');row.append(name,detail);$('capabilities').append(row);}$('crew-focus').onclick=()=>{follow=true;closePanel();};$('crew-talk').onclick=()=>openPanel('comms');}
 function settingsPanel(){$('panel-body').innerHTML='<p class="muted">New Horizon uses a fresh visual client and new assets. The existing mechanics document and sidecar remain the source of truth.</p><span class="field-label">Lighting quality</span><select id="quality"><option value="high">High</option><option value="medium">Balanced</option><option value="low">Low</option></select><div class="action-row"><button class="action" id="diagnostics">Capture diagnostics</button><button class="action" id="save-now">Save station</button></div><pre id="next-diagnostics" style="white-space:pre-wrap;font:12px VT323,monospace;color:#a3c6b2;overflow-wrap:anywhere"></pre>';$('quality').value=quality;$('quality').onchange=e=>quality=e.target.value;$('save-now').onclick=save;$('diagnostics').onclick=()=>{$('next-diagnostics').textContent=JSON.stringify({renderer:scene.stats(),art:{ready:art.ready,failures:art.failures},characters:characters.stats(),station:{rooms:Object.keys(station.rooms).length,props:station.props.length,belts:Object.keys(station.belts).length},actors:sim.actors().map(a=>({id:a.id,x:a.x,y:a.y,working:a.working,moving:a.moving,unplaced:a.unplaced})),connection:state.connection,save:state.save},null,2);};}
 function inspectProp(id){const p=model&&model.propById(id);if(!p){selectedProp=null;$('inspector').hidden=true;return;}selectedProp=id;const s=specs.get(p.t);$('inspector').hidden=false;$('inspector').innerHTML='<button class="close" aria-label="Close object details">×</button><span class="eyebrow">'+esc(s?.tier==='functional'?'STATION EQUIPMENT':'STATION OBJECT')+'</span><h2>'+esc(p.label||s?.label||p.t)+'</h2><p class="muted">'+esc(s?.desc||'')+'</p><div class="meta-pair"><span>Footprint</span><span>'+p.w+' × '+p.h+' tiles</span></div><div class="meta-pair"><span>Facing</span><span>'+['South','West','North','East'][p.r||0]+'</span></div><div class="action-row"><button class="action" id="rotate-prop">Turn</button><button class="action" id="mirror-prop">Mirror</button><button class="action danger" id="remove-prop">Remove</button></div><div id="prop-options"></div>';$('inspector').querySelector('.close').onclick=()=>{$('inspector').hidden=true;selectedProp=null;};$('rotate-prop').disabled=!s?.canRotate;$('mirror-prop').disabled=!NextOrientation.canMirror(s);$('rotate-prop').onclick=()=>{const next=NextOrientation.nextFacing(s,p.r);changed(model.faceProp(id,next,NextOrientation.box(s,next)));};$('mirror-prop').onclick=()=>changed(model.mirrorProp(id));$('remove-prop').onclick=()=>changed(model.removeProp(id));const box=$('prop-options');
  if(s?.cat==='workstation'||p.t==='bay'){box.innerHTML='<span class="field-label">Assigned crew</span><select id="assign-crew"><option value="">Unassigned</option>'+roster().map(a=>'<option value="'+esc(aid(a))+'" '+(p.agentId===aid(a)?'selected':'')+'>'+esc(a.name||aid(a))+'</option>').join('')+'</select><span class="field-label">Task brief</span><textarea id="prop-brief" aria-label="Object task brief">'+esc(p.brief||'')+'</textarea><button class="action" id="save-brief">Save brief</button>';$('assign-crew').onchange=e=>changed(model.assignPropAgent(id,e.target.value||null));$('save-brief').onclick=()=>changed(model.setPropBrief(id,$('prop-brief').value));}
  if(p.t==='airlock'){box.innerHTML='<span class="field-label">Airlock state</span><select id="door-state">'+['open','closed'].map(x=>'<option '+(p.door===x?'selected':'')+'>'+x+'</option>').join('')+'</select>';$('door-state').onchange=e=>changed(model.setDoorState(id,e.target.value));}
  if(['filter','merger','splitter','joiner','loop'].includes(p.t)){const input=document.createElement('textarea');input.setAttribute('aria-label','Junction configuration');input.value=JSON.stringify({routes:p.routes||{},def:p.def||'e',bufferSize:p.bufferSize??2,timeoutMin:p.timeoutMin,maxIter:p.maxIter,done:p.done,when:p.when},null,2);const b=document.createElement('button');b.className='action';b.textContent='Save routing configuration';b.onclick=()=>{try{changed(model.configureJunction(id,JSON.parse(input.value)));}catch(e){toast(e.message);}};box.append(input,b);}
 }
 function propAt(t){const id=model&&model.propAt(t.x,t.y);return typeof id==='string'?model.propById(id):id;}
 function act(start,end){if(!model)return;const p=propAt(start),rid=model.roomAt(start.x,start.y);if(tool==='prop'){const s=specs.get(armedType),box=NextOrientation.box(s,rotation);changed(model.addProp({t:s.id,x:end.x,y:end.y,w:box.w,h:box.h,block:s.blocks!==false,r:rotation}));}
  else if(tool==='room'){const r=rect(start,end);changed(model.addRoom({kind:roomKind,rect:r}));}
  else if(tool==='hall'){let r;if(Math.abs(end.x-start.x)>Math.abs(end.y-start.y))r={x1:Math.min(start.x,end.x),x2:Math.max(start.x,end.x),y1:start.y,y2:start.y+1};else r={x1:start.x,x2:start.x+1,y1:Math.min(start.y,end.y),y2:Math.max(start.y,end.y)};changed(model.placeHallway({rect:r}));}
  else if(tool==='paint'){if(rid)changed(model.setDeck(rid,{style:finish,mat:material}));}
  else if(tool==='erase'){if(p)changed(model.removeProp(p.id));else if(rid)changed(model.removeRoom(rid));}
  else if(tool==='move'){if(p)changed(model.moveProp(p.id,end.x-start.x,end.y-start.y));else if(rid)changed(model.moveRoom(rid,end.x-start.x,end.y-start.y));}
  else if(tool==='belt'){if(!p)return toast('Select a conveyor machine.');if(!beltFrom){beltFrom=p.id;toast('Now select the destination machine.');}else{changed(model.connectBelt(beltFrom,p.id));beltFrom=null;}}
  else if(p)inspectProp(p.id);
 }
 canvas.addEventListener('contextmenu',e=>e.preventDefault());
 canvas.addEventListener('pointerdown',e=>{if(!model)return;const p=point(e),t=tile(e);if(e.shiftKey){if(!sim.move(selectedAgent,t.x,t.y))toast('There is no clear walking route.');return;}canvas.setPointerCapture(e.pointerId);follow=false;drag={sx:e.clientX,sy:e.clientY,cx:camera.x,cy:camera.y,start:t,button:e.button,edit:panel==='build'&&tool!=='select'&&e.button===0,moved:false};if(!drag.edit&&e.button===0){const a=sim.actors().find(a=>Math.hypot(a.x*32-p.x,(a.y*32-26)-p.y)<28);if(a){selectedAgent=a.id;openPanel('comms');crewState();drag=null;}}});
 canvas.addEventListener('pointermove',e=>{if(!drag){if(panel==='build'&&tool==='prop'){const t=tile(e),s=specs.get(armedType);const box=NextOrientation.box(s,rotation);preview={x:t.x,y:t.y,w:box.w,h:box.h,t:s.id,r:rotation,valid:model.canPlaceProp(s.id,t.x,t.y,box.w,box.h).ok};}return;}const dx=e.clientX-drag.sx,dy=e.clientY-drag.sy;if(Math.hypot(dx,dy)>4)drag.moved=true;if(drag.edit){const r=rect(drag.start,tile(e));preview={x:r.x1,y:r.y1,w:r.x2-r.x1+1,h:r.y2-r.y1+1,valid:true};}else if(drag.moved){camera.x=drag.cx-dx/camera.zoom;camera.y=drag.cy-dy/camera.zoom;}});
 canvas.addEventListener('pointerup',e=>{if(!drag)return;const d=drag;drag=null;preview=null;if(d.edit)act(d.start,tile(e));else if(!d.moved&&e.button===0){const p=propAt(tile(e));if(p)inspectProp(p.id);else{$('inspector').hidden=true;selectedProp=null;}}});
 canvas.addEventListener('pointercancel',()=>{drag=null;preview=null;});
 canvas.addEventListener('wheel',e=>{e.preventDefault();const before=point(e);camera.zoom=Math.min(2.4,Math.max(.2,camera.zoom*Math.exp(-e.deltaY*.0012)));const after=point(e);camera.x+=before.x-after.x;camera.y+=before.y-after.y;follow=false;},{passive:false});
 window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='Escape'){closePanel();$('inspector').hidden=true;selectedProp=null;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();changed(e.shiftKey?model.redo():model.undo());}if(e.key.toLowerCase()==='r'&&panel==='build'){rotation=NextOrientation.nextFacing(specs.get(armedType),rotation);if(tool==='prop')buildPanel();}if(e.key.toLowerCase()==='b')openPanel('build');if(e.key.toLowerCase()==='m')fit();});
 $('overview').onclick=fit;$('focus').onclick=()=>follow=!follow;$('panel-close').onclick=closePanel;$('crew-manage').onclick=()=>openPanel('crew');$('undo').onclick=()=>changed(model.undo());$('redo').onclick=()=>changed(model.redo());$('settings').onclick=()=>openPanel('settings');document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>panel===b.dataset.panel?closePanel():openPanel(b.dataset.panel));
 bridge.subscribe(next=>{state=next;const status=next.connection?.status||'connecting';$('connection').dataset.state=status;$('connection').textContent=['connected','online'].includes(status)?'Station link online':status==='connecting'?'Connecting to station':'Station link unavailable';if(next.station&&localRevision===savedRevision&&JSON.stringify(next.station)!==stationKey){const first=!model;model=WorldModel.deserialize(next.station);updateStation(model.serialize());if(first){focusRoom(station.meta.spawnRoomId);$('loading').hidden=!!art&&!!characters;}}const rk=JSON.stringify(roster());if(rk!==rosterKey){rosterKey=rk;sim.setRoster(roster());if(!selectedAgent&&roster().length)selectedAgent=aid(roster()[0]);}sim.updateWork(next.runs||[],online());crewState();renderMessages();renderPrompts();if(next.connection?.error)$('loading-message').textContent=next.connection.error;});
 try{[art,characters]=await Promise.all([NextArt.create(),NextCharacters.create()]);art=Object.assign({},art,{drawAgent:(ctx,a,t)=>characters.draw(ctx,a,t)});$('loading-message').textContent='Fresh assets loaded. Recovering the station document.';await bridge.start();if(model){$('loading').hidden=true;$('save-state').textContent='Station loaded';delete $('crew-list').dataset.signature;crewState();}else $('loading-message').textContent='No station document is available. Open an existing saved station on this sidecar.';}
 catch(e){$('loading-message').textContent=e.message;console.error('New Horizon boot:',e);return;}
 function draw(now){const dt=(now-last)/1000;last=now;const actors=sim.tick(dt);if(follow){const a=actors.find(a=>a.id===selectedAgent);if(a){camera.x+=(a.x*32-camera.x)*Math.min(1,dt*4);camera.y+=(a.y*32-40-camera.y)*Math.min(1,dt*4);}}if(station)scene.draw({station,agents:actors,props:renderedProps,now,camera,width:innerWidth,height:innerHeight,selection:selectedProp||selectedAgent,preview,quality,reducedMotion:matchMedia('(prefers-reduced-motion:reduce)').matches},art);if(now-lastDom>300){crewState();lastDom=now;}requestAnimationFrame(draw);}requestAnimationFrame(draw);
 window.NextApp=Object.freeze({snapshot:()=>({station:model&&model.serialize(),actors:sim.actors().map(a=>({...a,path:a.path.slice()})),bridge:bridge.snapshot(),renderer:scene.stats(),camera:{...camera},art:{ready:art.ready,failures:art.failures},characters:characters.stats()}),generation:'fresh-client',legacyVisualModules:[]});
})().catch(e=>{const m=document.getElementById('loading-message');if(m)m.textContent=e.message;console.error(e);});
